apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-admin-web
  namespace: mall
  labels:
    app: mall-admin-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-admin-web
  template:
    metadata:
      labels:
        app: mall-admin-web
    spec:
      containers:
        - name: mall-admin-web
          image: yt9999/mall-admin-web:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mall-admin-web
  namespace: mall
spec:
  selector:
    app: mall-admin-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mall-admin-web
  namespace: mall
spec:
  rules:
    - host: "mall-admin-web.mall-k8s.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: mall-admin-web
                port:
                  number: 80